### ISSUE TITLE
Decouple Provider Support

### ISSUE THREAD

**Issue by jtdroste** [ubnetdef/genesis#7]
Currently we're hardcoded into accepting VMware. It's in a weird hardcoded state.

Ideally, let's decouple this from VMware. We don't need to support other providers _right now_, but it should provide a path forward for us to do so (i.e., an AWS provider)

**Comment by djmurray1** [comment]
Support for Open Stack would be great for other institutions desiring to adopt this.

**Comment by jtdroste** [comment]
Done in 8dfa873.

Feature request for OpenStack / AWS is later.
